# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 114906b5c269fd4faa4f474737312c08a582d2022fd276c1c68f74d9aff638e32fb6cfed88c7e7cce8c6a982a5bb5105887d3c8d396a70ff2081a71b72ba0cb4

test:
  secret_key_base: bcb0e54c16669ebe28737bf14cc28abee7467285a244e56173a57df70d06bf6df45877736a026ca92b549a66ee0c87773e17081add18e864209ceb118e846489

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
